[package]
name = "imap_bodystructure"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
description = "The library for parsing various data formats in Rust, based on Nom."
repository = "https://github.com/coalooball/glot"
readme = "README.md"

[dependencies]
nom = "7.1.3"
